<?php

/**
 * @file
 * This is the adyax ws module to provide simple REST Service.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function adyax_ws_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.adyax_ws':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module implements simple REST Service') . '</p>';
      $output .= '<h3>' . t('Support next methods:') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('GET - returns JSON with data from node. NID provided in URL request, for example:  /adyax_ws?nid=123 ;') . '</dt>';
      $output .= '<dt>' . t('POST - retrieve JSON data with title, type and body and create new node based on provided data;') . '</dt>';
      $output .= '<dt>' . t('PUT - retrieve JSON data and update node by NID provided in JSON;') . '</dt>';
      $output .= '<dt>' . t('DELETE - deletes node by provided NID;') . '</dt>';
      $output .= '</dl>';
      return $output;
  }
}
